source "https://rubygems.org"

ruby "4.0.5"

gem "rails", "~> 7.1"
gem "sqlite3", "~> 1.6"
gem "puma", ">= 5.0"
gem "image_processing", "~> 1.2"
gem "rack-cors"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
  gem "rack-test"
end